<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>CreatorGame</AssemblyName>
    <RootNamespace>CreatorGame</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\managed\CreatorEngine.Managed\CreatorEngine.Managed.csproj" />
  </ItemGroup>
</Project>
