<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>CreatorEngine.Managed</AssemblyName>
    <RootNamespace>CreatorEngine</RootNamespace>
  </PropertyGroup>
</Project>
